name: Go unit test
description: Run unit tests in Go
inputs:
  dirs:
    description: A space-separated list of directories to test
    default: ./
    required: false
  cover-path:
    description: Path to the coverprofile
    required: false
    default: ./cover.out
runs:
  using: composite
  steps:
    - name: Go unit test
      uses: shell
      run: |
        go test -v -coverprofile=${{inputs.cover-path}} -covermode=atomic `find ${{inputs.dirs}} -type d -mindepth 1`
