name: Build and push image locally

inputs:
  image-name:
    required: true
    description: The name of the image e.g. 'pilot'
  host:
    required: true
    description: The hostname for the registry to push
  file:
    required: false
    default: Dockerfile
    description: The path to the Dockerfile to build
  context:
    required: false
    description: The Docker build context
    default: '.'
outputs:
  tag:
    description: The full tag built
    value: ${{ steps.meta.outputs.tags }}
runs:
  using: composite
  steps:
    - name: Docker meta
      uses: docker/metadata-action@v5
      id: meta
      with:
        images: |
          ${{ inputs.image-name }}
        tags: |
          type=raw,value=latest
    - name: Docker build and push
      uses: skiff-sh/gh-actions/docker-build-and-push@master
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        image-description: 'Local build of ${{ inputs.image-name}}'
        image-source: ${{ github.server_url }}/${{ github.repository }}
        push: false
        tags: ${{ steps.meta.outputs.tags }}
    - name: Push image to K3D
      shell: bash
      run: |
        docker tag ${{ inputs.image-name}}:latest ${{ inputs.host }}/${{ inputs.image-name }}:latest
        docker push ${{ inputs.host }}/${{ inputs.image-name }}:latest
