name: Build and push image locally

inputs:
  image-name:
    required: true
    description: The name of the image e.g. 'pilot'
  image-base:
    required: true
    description: The image base for the K3D cluster
  host:
    required: true
    description: The hostname for the registry to push
  file:
    required: false
    default: Dockerfile
    description: The path to the Dockerfile to build
  context:
    required: false
    description: The Docker build context
    default: '.'
outputs:
  image:
    description: The reference for the image in a K3D cluster
    value: '${{ inputs.image-base }}/${{ inputs.image-name }}:latest'
  tag:
    description: The full tag built
    value: ${{ steps.meta.outputs.tags }}
runs:
  using: composite
  steps:
    - name: Docker build and push
      uses: skiff-sh/gh-actions/docker-build-and-push@master
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        image-description: 'Local build of ${{ inputs.image-name}}'
        image-source: ${{ github.server_url }}/${{ github.repository }}
        push: true
        tags: ${{ inputs.host }}/${{ inputs.image-name }}:latest
