name: Setup K3D registry
outputs:
  host:
    description: The host to target for image tags
    value: 'localhost:8562'
  image-base:
    description: The image base to reference in a K3D cluster
    value: 'k3d-skiff:8562'

runs:
  using: composite
  steps:
    - name: Create local registry
      shell: bash
      run: |
        k3d registry create skiff -p 0.0.0.0:8562
        
