on:
  workflow_call:
    inputs:
      images:
        description: The list of images to push
        required: true
        type: string
      tags:
        description: List of tags for the images
        required: true
        type: string
      image-description:
        description: The description for the image
        required: true
        type: string
      push:
        description: Should we push the image after building it
        required: false
        type: string
        default: 'false'
      workflow-ref:
        description: If running this on a branch e.g. for testing, you can specify that branch here
        required: false
        default: ''
        type: string
      context:
        description: The Docker context
        required: false
        default: .
        type: string
      file:
        description: The Dockerfile
        required: false
        default: Dockerfile
        type: string
      platforms:
        description: List of platforms to target when building the container
        required: false
        default: ''
        type: string

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          token: '${{ github.token }}'
      - uses: skiff-sh/gh-actions/docker-setup@master
      - name: Docker meta
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ${{ inputs.images }}
          tags: |
            ${{ inputs.tags }}
      - name: Docker login
        uses: skiff-sh/gh-actions/docker-login@master
        with:
          registry: 'ghcr.io'
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker build and push
        uses: skiff-sh/gh-actions/docker-build-and-push@master
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          image-description: ${{ inputs.image-description }}
          image-source: ${{ github.server_url }}/${{ github.repository }}
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          platforms: ${{ inputs.platforms }}
